package com.tracker;

import java.time.LocalDateTime;

public class Task {
    private static Integer nextId = 1;

    private Integer id;
    private String description;
    private String status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Task (String description, String status) {
        this.id = nextId++;
        this.description = description;
        this.status = status;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    public Integer getId() {
        return id;
    }

    /* (Optional) Package-private setter for persistence frameworks (e.g., JPA/Hibernate)
    This is often used by ORMs to set the ID after it's generated by the database. */
    void setId(Integer id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    // Getter for updatedAt, but NO setter
    public LocalDateTime getUpdatedAt() { return updatedAt; }

    // Internal method to update updatedAt (called from DAO)
    void updateUpdatedAt() {
        this.updatedAt = LocalDateTime.now();
    }
}
