package com.dominik.tasktracker;

import java.time.LocalDateTime;

public class Task {
    private Integer id;
    private String description;
    private String status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Task(String description, String status) {
        this.description = description;
        this.status = status;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    public Integer getId() {
        return id;
    }

    /* (Optional) Package-private setter for persistence frameworks (e.g., JPA/Hibernate)
    This is often used by ORMs to set the ID after it's generated by the database. */
    void setId(Integer id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    @SuppressWarnings("unused")
    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    @SuppressWarnings("unused")
    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Getter for updatedAt, but NO setter
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    // Internal method to update updatedAt (called from DAO)
    void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
